services:
  book.api:
    image: bookapi
    build:
      context: .
      dockerfile: Book.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=book-db;Database=bookify;User Id=sa;Password=AidaAlipoor@1;TrustServerCertificate=True;
    depends_on:
      - book-db

  book-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: book-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AidaAlipoor@1
    ports:
      - "14330:1433"    
